defaults: &defaults
  python_path: /usr/local/bin/python2.6
  tmp_file_path: /var/www/html/RailsTest/model/my_data
  script_path: /var/www/html/RailsTest/model/my_data/convert_to_threejs.py
  

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults